"""
Patient Data Schemas

Defines data structures for patient profiles and refill predictions.
Uses Pydantic for validation and documentation.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import date
from enum import Enum


class BehaviorType(str, Enum):
    """Patient refill behavior classification."""
    HIGHLY_REGULAR = "highly_regular"
    REGULAR = "regular"
    IRREGULAR = "irregular"
    NEW_PATIENT = "new_patient"
    INSUFFICIENT_DATA = "insufficient_data"


class RefillPattern(BaseModel):
    """Statistical analysis of a patient's refill pattern."""
    
    average_interval_days: float = Field(
        ..., 
        description="Average days between refills"
    )
    std_deviation_days: float = Field(
        ..., 
        description="Standard deviation of refill intervals"
    )
    total_refills: int = Field(
        ..., 
        description="Total number of refills in history"
    )
    consistency_score: float = Field(
        ..., 
        ge=0, 
        le=1, 
        description="How consistent the patient is (0-1)"
    )


class RefillPrediction(BaseModel):
    """Prediction for a patient's next refill."""
    
    expected_date: date = Field(
        ..., 
        description="Most likely refill date"
    )
    confidence: float = Field(
        ..., 
        ge=0, 
        le=1, 
        description="Confidence in prediction (0-1)"
    )
    earliest_date: date = Field(
        ..., 
        description="Earliest likely refill date (lower bound)"
    )
    latest_date: date = Field(
        ..., 
        description="Latest likely refill date (upper bound)"
    )
    days_until_expected: int = Field(
        ..., 
        description="Days from today until expected refill"
    )


class PatientProfile(BaseModel):
    """
    Complete profile of a patient's medication behavior.
    
    Generated by the Patient Profiling Agent for use by
    downstream agents (Forecasting, Optimization).
    """
    
    patient_id: str = Field(
        ..., 
        description="Unique patient identifier"
    )
    medication: str = Field(
        ..., 
        description="Medication name and dosage"
    )
    behavior_type: BehaviorType = Field(
        ..., 
        description="Classified behavior pattern"
    )
    pattern: RefillPattern = Field(
        ..., 
        description="Statistical refill pattern"
    )
    prediction: Optional[RefillPrediction] = Field(
        None, 
        description="Next refill prediction (None if insufficient data)"
    )
    last_fill_date: date = Field(
        ..., 
        description="Date of most recent refill"
    )
    last_quantity: int = Field(
        ..., 
        description="Quantity of most recent refill"
    )
    is_due_soon: bool = Field(
        False, 
        description="True if refill expected within 7 days"
    )
    risk_of_lapse: float = Field(
        0.0, 
        ge=0, 
        le=1, 
        description="Risk patient will miss next refill"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "patient_id": "P0001",
                "medication": "Metformin 500mg",
                "behavior_type": "regular",
                "pattern": {
                    "average_interval_days": 30.5,
                    "std_deviation_days": 3.2,
                    "total_refills": 11,
                    "consistency_score": 0.85
                },
                "prediction": {
                    "expected_date": "2024-11-25",
                    "confidence": 0.82,
                    "earliest_date": "2024-11-22",
                    "latest_date": "2024-11-28",
                    "days_until_expected": 5
                },
                "last_fill_date": "2024-10-26",
                "last_quantity": 60,
                "is_due_soon": True,
                "risk_of_lapse": 0.08
            }
        }


class PatientProfilingResult(BaseModel):
    """
    Complete output from Patient Profiling Agent.
    
    Contains all patient profiles plus summary statistics.
    """
    
    profiles: List[PatientProfile] = Field(
        ..., 
        description="List of all patient profiles"
    )
    total_patients: int = Field(
        ..., 
        description="Total unique patients analyzed"
    )
    total_patient_medications: int = Field(
        ..., 
        description="Total patient-medication combinations"
    )
    patients_due_soon: int = Field(
        ..., 
        description="Patients with refill expected within 7 days"
    )
    analysis_date: date = Field(
        ..., 
        description="Date analysis was performed"
    )
    
    def get_due_soon(self) -> List[PatientProfile]:
        """Get profiles for patients due for refill within 7 days."""
        return [p for p in self.profiles if p.is_due_soon]
    
    def get_by_medication(self, medication: str) -> List[PatientProfile]:
        """Get all profiles for a specific medication."""
        return [p for p in self.profiles if p.medication == medication]
    
    def get_high_risk(self, threshold: float = 0.2) -> List[PatientProfile]:
        """Get profiles with high lapse risk."""
        return [p for p in self.profiles if p.risk_of_lapse >= threshold]